"""add sender_name to messages and make sender_id nullable

Revision ID: f7594d462249
Revises: 123456789abc
Create Date: 2026-07-01 20:18:05.826432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7594d462249'
down_revision: Union[str, None] = '123456789abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_name', sa.String(length=255), nullable=False))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'sender_name')
    # ### end Alembic commands ###
